human_resource/accounts/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from accounts.views import LoginView, SignupView, LogoutView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^signup/$', SignupView.as_view(), name='signup'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),

]

urlpatterns += staticfiles_urlpatterns()

human_resource/administration/urls.py
# import user

from django.conf.urls import url
from . import views

urlpatterns = [
    # user roles urls

    url(r'^$', views.UserRoleListView.as_view(), name='user_role_landing'),
    url(r"create$", views.CreateUserRoleView.as_view(), name='create_user_role'),

    #employee urls
    url(r'^$', views.EmployeeListView.as_view(), name='employee_landing'),
    url(r"create$", views.CreateEmployeeView.as_view(), name='create_employee'),

    # system users urls
    url(r'^$', views.UserListView.as_view(), name='user_landing'),
    url(r"create$", views.CreateUserView.as_view(), name='create_users'),

    # job titles urls
    url(r'^$', views.JobTitleListView.as_view(), name='job_title_landing'),
    url(r"create$", views.CreateUserView.as_view(), name='create_job_title'),

    # job category urls
    url(r'^$', views.JobCategoryListView.as_view(), name='job_category_landing'),
    url(r"create$", views.CreateJobCategoryView.as_view(), name='create_job_category'),

    # work shifts urls
    url(r'^$', views.WorkShiftListView.as_view(), name='work_shift_landing'),
    url(r"create$", views.CreateWorkShiftView.as_view(), name='create_work_shift'),

]

human_resource/human_resource/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from human_resource import views

urlpatterns = [
    url(r'^$', views.home, name='landing'),
    url(r'^admin_menu/', views.admin_menu, name='admin_menu'),

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^administration/', include('administration.urls', namespace='administration')),

]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

human_resource/administration/models.py
from django.db import models


class UserRole(models.Model):
    role_name = models.CharField(max_length=50, unique=True)
    description = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.role_name


class Employee(models.Model):
    employee_name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='media/employee_images')
    user_role = models.ForeignKey(UserRole)

    def __str__(self):
        return self.employee_name

    def get_image_url(self):
        img = self.employeeimage_set.first()
        if img:
            return img.image.url
        return img


class User(models.Model):
    username = models.CharField(max_length=100, unique=True)
    user_role = models.ForeignKey(UserRole)
    employee_name = models.ForeignKey(Employee)
    status = models.BooleanField(default=True)
    password = models.CharField(max_length=100, unique=True)
    confirm_password = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.username


class JobTitle(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=100, unique=True)
    specification = models.FileField(upload_to='media/jobs_specifications')

    def __str__(self):
        return self.title


class JobCategory(models.Model):
    category_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.category_name





WEEKDAYS = [
  (1, ("Monday")),
  (2, ("Tuesday")),
  (3, ("Wednesday")),
  (4, ("Thursday")),
  (5, ("Friday")),
  (6, ("Saturday")),
  (7, ("Sunday")),
]

class WorkShift(models.Model):
    shift_name = models.CharField(max_length=100, unique=True)
    weekday = models.IntegerField(choices=WEEKDAYS)
    from_hour = models.TimeField()
    to_hour = models.TimeField()

    class Meta:
        ordering = ('weekday', 'from_hour')
        unique_together = ('weekday', 'from_hour', 'to_hour')

    def __str__(self):
        return u'%s: %s - %s' % (self.get_weekday_display(),
                                 self.from_hour, self.to_hour)

    def __str__(self):
        return self.shift_name

human_resource/administration/forms.py
from django.forms import forms

from administration.models import UserRole, WEEKDAYS


class UserRolesForm(forms.Model):
    class Meta:
        role_name = forms.CharField(max_length=50, unique=True)
        description = forms.TextField(null=True, blank=True)
        active = forms.BooleanField(default=True)


class Employee(forms.Model):
    class Meta:
        employee_name = forms.CharField(max_length=100, unique=True)
        image = forms.ImageField(upload_to='media/employee_images')
        user_role = forms.ForeignKey(UserRole)


class User(forms.Model):
    class Meta:
        username = forms.CharField(max_length=100, unique=True)
        user_role = forms.ForeignKey(UserRole)
        employee_name = forms.ForeignKey(Employee)
        status = forms.BooleanField(default=True)
        password = forms.CharField(max_length=100, unique=True)
        confirm_password = forms.CharField(max_length=100, unique=True)


class JobTitle(forms.Model):
    class Meta:
        title = forms.CharField(max_length=100, unique=True)
        description = forms.CharField(max_length=100, unique=True)
        specification = forms.FileField(upload_to='media/jobs_specifications')


class JobCategory(forms.Model):
    class Meta:
        category_name = forms.CharField(max_length=100, unique=True)

class WorkShift(forms.Model):
    class Meta:
        shift_name = forms.CharField(max_length=100, unique=True)
        weekday = forms.IntegerField(choices=WEEKDAYS)
        from_hour = forms.TimeField()
        to_hour = forms.TimeField()

human_resource/administration/views.py
# Create your views here.

from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView

from administration.models import UserRole, User, JobTitle, JobCategory, WorkShift


class CreateUserRoleView(CreateView):
    model = UserRole
    fields = ['role_name', 'description', 'active']
    success_url = reverse_lazy("administration:user_role_landing")
    template_name = 'administration/create_user_role.html'


class UserRoleListView(ListView):
    model = UserRole
    template_name = 'administration/user_role_landing.html'


class CreateEmployeeView(CreateView):
    model = UserRole
    fields = ['employee_name', 'image', 'user_role']
    success_url = reverse_lazy("administration:employee_landing")
    template_name = 'administration/create_employee.html'


class EmployeeListView(ListView):
    model = UserRole
    template_name = 'administration/employee_landing.html'


class CreateUserView(CreateView):
    model = User
    fields = ['username', 'user_role', 'employee_name', ' status', 'password', ' confirm_password']
    success_url = reverse_lazy("administration:user_landing")
    template_name = 'admininstration/create_users.html'


class UserListView(ListView):
    model = User
    template_name = 'administration/user_landing.html'


class CreateJobTitleView(CreateView):
    model = JobTitle
    fields = ['title', 'description', 'specification', ' status', 'password', ' confirm_password']
    success_url = reverse_lazy("administration:job_title_landing")
    template_name = 'admininstration/create_job_title.html'


class JobTitleListView(ListView):
    model = JobTitle
    template_name = 'administration/job_title_landing.html'



class CreateJobCategoryView(CreateView):
    model = JobCategory
    success_url = reverse_lazy("administration:job_category_landing")
    template_name = 'administration/create_job_category.html'

class JobCategoryListView(ListView):
    model = JobCategory
    template_name = 'administration/job_category_landing.html'

class CreateWorkShiftView(CreateView):
    model = WorkShift
    fields = ['shift_name','weekday','from_hour',' to_hour']
    success_url = reverse_lazy('administration:work_shift_landing')
    template_name = 'administration/create_work_shift.html'

class WorkShiftListView(ListView):
    model = WorkShift
    template_name = 'administration/work_shift_landing.html'

human_resource/administration/templates/administration/create_employee.html
{% extends 'admin_menu.html' %}
{% load bootstrap3 %}

{% block title %} Add Employee{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
    <h3>Add Employee</h3>
    <!--align="center"-->
    <form method="post"  >
        {% csrf_token %}
        {% bootstrap_form form %}


        <input type="submit" value="Add Employee" class="btn btn-primary">

        <a href="#"class="btn btn-primary"> Cancel</a>
    </form>
{% else %}
{% endif %}
{% endblock %}

human_resource/administration/templates/administration/create_job_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

human_resource/administration/templates/administration/create_job_title.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

human_resource/administration/templates/administration/create_user_role.html
{% extends 'admin_menu.html' %}
{% load bootstrap3 %}

{% block title %} Add User Role{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
    <h3>Add USer Role</h3>
    <!--align="center"-->
    <form method="post"  >
        {% csrf_token %}
        {% bootstrap_form form %}


        <input type="submit" value="Add User Role" class="btn btn-primary">

        <a href="#"class="btn btn-primary"> Cancel</a>
    </form>
{% else %}
{% endif %}
{% endblock %}

human_resource/administration/templates/administration/create_users.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %} Add Category{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
    <h3>Add USer</h3>
    <!--align="center"-->
    <form method="post"  >
        {% csrf_token %}
        {% bootstrap_form form %}


        <input type="submit" value="Add User" class="btn btn-primary">

        <a href="#"class="btn btn-primary"> Cancel</a>
    </form>
{% else %}
{% endif %}
{% endblock %}

human_resource/administration/templates/administration/create_work_shift.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

human_resource/administration/templates/administration/employee_landing.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block title %} Employees {% endblock %}

{% block content %}
    <div class="page-header" align="center" xmlns="http://www.w3.org/1999/html">
        <h2> Employees</h2>
    </div>
    <div class="container">


        <div class="panel-body">
            <div class="col-md-6">
                <div id="search_block_top">
                    <div id="search_block_top_wrap">
                        <form id="searchbox" method="get"
                              action="#" class="navbar-form navbar-left" autocomplete="on">
                            <div class="form-group"><input style="width: 250px; height: 40px"
                                                           class="search_query form-control" type="text"
                                                           id="search_query_top"
                                                           placeholder="Enter User Role Name" name="search"/></div>
                            <button type="submit" class="btn btn-success button-search">Search For Employees</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="pull-right">
                <a href="#" align="pull-right"
                   class="btn btn-success"
                   role="button"><span class="glyphicon glyphicon-plus"></span>Employee List</a>
            </div>
        </div>


        <table class="table table-hover" id="dev-table">
            <thead>
            <tr>

                <th>ID</th>
                <th>Image</th>
                <th>Employee Name</th>
                <th>User Role</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for employee in object_list %}
                <tr>
                    <td>
                        {{ employee.id|capfirst }}
                    </td>
                    <td>
                        {{ employee.image }}
                    </td>

                    <td>
                        {{ employee.employee_name|capfirst }}
                    </td>

                    <td>
                        {{ employee.user_role|capfirst }}
                    </td>


                    <td class="text-center">
                        <a class='btn btn-success btn-xs'
                           href="#"><span
                                class="glyphicon glyphicon-edit"></span> Edit
                        </a>

                    </td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

{% endblock %}

human_resource/administration/templates/administration/job_category_landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

human_resource/administration/templates/administration/job_title_landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

human_resource/administration/templates/administration/user_landing.html
{% extends 'admin_menu.html' %}

{% load static from staticfiles %}

{% block title %} User Roles {% endblock %}

{% block content %}
    <div class="page-header" align="center" xmlns="http://www.w3.org/1999/html">
        <h2> User Roles</h2>
    </div>
    <div class="container">


        <div class="panel-body">
            <div class="col-md-6">
                <div id="search_block_top">
                    <div id="search_block_top_wrap">
                        <form id="searchbox" method="get"
                              action="#" class="navbar-form navbar-left" autocomplete="on">
                        <div class="form-group"><input style="width: 250px; height: 40px"
                                    class="search_query form-control" type="text"
                                    id="search_query_top"
                                    placeholder="Enter User Role Name" name="search"/></div>
                            <button type="submit" class="btn btn-success button-search">Search For Sellers</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="pull-right">
                <a href="#" align="pull-right"
                   class="btn btn-success"
                   role="button"><span class="glyphicon glyphicon-plus"></span>Sellers Products List </a>
            </div>
        </div>


        <table class="table table-hover" id="dev-table">
            <thead>
            <tr>

                <th>ID</th>
                <th>Role Name</th>
                <th>Description</th>
                <th>Status</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for userrole in userrole_list %}
                <tr>
                    <td>
                        {{ userrole.id|capfirst }}
                    </td>

                    <td>
                        {{ userrole.role_name|capfirst }}
                    </td>
                    <td>
                        {{ userrole.description|capfirst }}
                    </td>
                    <td>
                        {{ userrole.active|capfirst }}
                    </td>


                    <td class="text-center">
                        <a class='btn btn-success btn-xs'
                           href="#"><span
                                class="glyphicon glyphicon-edit"></span> Edit
                        </a>
                        <a href="#"
                           class="btn btn-primary btn-xs"><span
                                class="glyphicon glyphicon-remove"></span> Delete
                        </a>
                        <a href="#"
                           class="btn btn-danger btn-xs"><span
                                class="glyphicon glyphicon-folder-open"></span> Details
                        </a>
                    </td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

{% endblock %}

human_resource/administration/templates/administration/user_role_landing.html
{% extends 'admin_menu.html' %}

{% load static from staticfiles %}

{% block title %} User Roles{% endblock %}

{% block content %}
    <div class="page-header" align="center" xmlns="http://www.w3.org/1999/html">
        <h2> User Roles</h2>
    </div>
    <div class="container">


{#        <div class="panel-body">#}
{#            <div class="col-md-6">#}
{#                <div id="search_block_top">#}
{#                    <div id="search_block_top_wrap">#}
{#                        <form id="searchbox" method="get"#}
{#                              action="#" class="navbar-form navbar-left" autocomplete="on">#}
{#                            <div class="form-group"><input style="width: 250px; height: 40px"#}
{#                                                           class="search_query form-control" type="text"#}
{#                                                           id="search_query_top"#}
{#                                                           placeholder="Enter Users " name="search"/></div>#}
{#                            <button type="submit" class="btn btn-success button-search">Search For Users</button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}


        <table class="table table-hover" id="dev-table">
            <thead>
            <tr>

                <th>ID</th>
                <th>Username</th>
                <th>User Role</th>
                <th>Employee Name</th>
                <th>Status</th>

                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for userrole in user_role_landing %}
                <tr>
                    <td>
                        {{ userrole.id|capfirst }}
                    </td>
                    <td>
                        {{ userrole.user_name|capfirst }}
                    </td>
                    <td>
                        {{ userrole.user_role|capfirst }}
                    </td>
                    <td>
                        {{ userrole.employee_name|capfirst }}
                    </td>
                    <td>
                        {{ userrole.status|capfirst }}
                    </td>


                    <td class="text-center">
                        <a class='btn btn-success btn-xs'
                           href="#"><span
                                class="glyphicon glyphicon-edit"></span> Edit
                        </a>
                        <a href="#"
                           class="btn btn-primary btn-xs"><span
                                class="glyphicon glyphicon-remove"></span> Delete
                        </a>

                    </td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

{% endblock %}

human_resource/administration/templates/administration/work_shift_landing.html
{% extends 'admin_menu.html' %}

{% load static from staticfiles %}

{% block title %} User Roles{% endblock %}

{% block content %}
    <div class="page-header" align="center" xmlns="http://www.w3.org/1999/html">
        <h2> User Roles</h2>
    </div>
    <div class="container">


{#        <div class="panel-body">#}
{#            <div class="col-md-6">#}
{#                <div id="search_block_top">#}
{#                    <div id="search_block_top_wrap">#}
{#                        <form id="searchbox" method="get"#}
{#                              action="#" class="navbar-form navbar-left" autocomplete="on">#}
{#                            <div class="form-group"><input style="width: 250px; height: 40px"#}
{#                                                           class="search_query form-control" type="text"#}
{#                                                           id="search_query_top"#}
{#                                                           placeholder="Enter Users " name="search"/></div>#}
{#                            <button type="submit" class="btn btn-success button-search">Search For Users</button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}


        <table class="table table-hover" id="dev-table">
            <thead>
            <tr>

                <th>ID</th>
                <th>Username</th>
                <th>User Role</th>
                <th>Employee Name</th>
                <th>Status</th>

                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for workshift in workshift_list %}
                <tr>    fields = ['shift_name','weekday','from_hour',' to_hour']

                    <td>
                        {{ workshift.id|capfirst }}
                    </td>
                    <td>
                        {{ workshift.shift_name|capfirst }}
                    </td>
                    <td>
                        {{ workshift.user_role|capfirst }}
                    </td>
                    <td>
                        {{ workshift.employee_name|capfirst }}
                    </td>
                    <td>
                        {{ workshift.status|capfirst }}
                    </td>


                    <td class="text-center">
                        <a class='btn btn-success btn-xs'
                           href="#"><span
                                class="glyphicon glyphicon-edit"></span> Edit
                        </a>
                        <a href="#"
                           class="btn btn-primary btn-xs"><span
                                class="glyphicon glyphicon-remove"></span> Delete
                        </a>

                    </td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

{% endblock %}