human_resource/accounts/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from accounts.views import LoginView, SignupView, LogoutView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^signup/$', SignupView.as_view(), name='signup'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),

]

urlpatterns += staticfiles_urlpatterns()

human_resource/human_resource/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from human_resource import views

urlpatterns = [
    url(r'^$', views.home, name='landing'),
    url(r'^admin_menu/', views.admin_menu, name='admin_menu'),

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^administration/', include('administration.urls', namespace='administration')),

]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

human_resource/accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

human_resource/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = User

human_resource/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import FormView, CreateView, RedirectView
from .forms import UserCreateForm


class SignupView(CreateView):
    template_name = 'accounts/signup.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('accounts:login')

    def dispatch(self, request, *args, **kwargs):
        return super(SignupView, self).dispatch(request, *args, **kwargs)

signup = SignupView.as_view()


class LoginView(FormView):
    template_name = 'accounts/login.html'
    success_url =   reverse_lazy('home')
    form_class = AuthenticationForm

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.form_class
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)
        #return HttpResponseRedirect(self.get_success_url())


class LogoutView(RedirectView):
    url = reverse_lazy('accounts:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

human_resource/accounts/templates/accounts/account_inactive.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account Inactive" %}{% endblock %}

{% block content %}
<h1>{% trans "Account Inactive" %}</h1>

<p>{% trans "This accounts is inactive." %}</p>
{% endblock %}

human_resource/accounts/templates/accounts/email.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account" %}{% endblock %}

{% block content %}
    <h1>{% trans "E-mail Addresses" %}</h1>
{% if user.emailaddress_set.all %}
<p>{% trans 'The following e-mail addresses are associated with your accounts:' %}</p>

<form action="{% url 'account_email' %}" class="email_list" method="post">
{% csrf_token %}
<fieldset class="blockLabels">

  {% for emailaddress in user.emailaddress_set.all %}
<div class="ctrlHolder">
      <label for="email_radio_{{forloop.counter}}" class="{% if emailaddress.primary %}primary_email{%endif%}">

      <input id="email_radio_{{forloop.counter}}" type="radio" name="email" {% if emailaddress.primary or user.emailaddress_set.count == 1 %}checked="checked"{%endif %} value="{{emailaddress.email}}"/>

{{ emailaddress.email }}
    {% if emailaddress.verified %}
    <span class="verified">{% trans "Verified" %}</span>
    {% else %}
    <span class="unverified">{% trans "Unverified" %}</span>
    {% endif %}
      {% if emailaddress.primary %}<span class="primary">{% trans "Primary" %}</span>{% endif %}
</label>
</div>
  {% endfor %}

<div class="buttonHolder">
      <button class="secondaryAction" type="submit" name="action_primary" >{% trans 'Make Primary' %}</button>
      <button class="secondaryAction" type="submit" name="action_send" >{% trans 'Re-send Verification' %}</button>
      <button class="primaryAction" type="submit" name="action_remove" >{% trans 'Remove' %}</button>
</div>

</fieldset>
</form>

{% else %}
<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc." %}</p>

{% endif %}


    <h2>{% trans "Add E-mail Address" %}</h2>

    <form method="post" action="{% url 'account_email' %}" class="add_email">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="action_add" type="submit">{% trans "Add E-mail" %}</button>
    </form>

{% endblock %}


{% block extra_body %}
<script type="text/javascript">
(function() {
  var message = "{% trans 'Do you really want to remove the selected e-mail address?' %}";
  var actions = document.getElementsByName('action_remove');
  if (actions.length) {
    actions[0].addEventListener("click", function(e) {
      if (! confirm(message)) {
        e.preventDefault();
      }
    });
  }
})();
</script>
{% endblock %}

human_resource/accounts/templates/accounts/email_confirm.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block content %}
<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

human_resource/accounts/templates/accounts/login.html
{% extends "../../../landing.html" %}

{% load i18n %}
{% load bootstrap3 %}

{% block head_title %}Login {% endblock %}

{% block content %}
    <div class="container">
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title" >Spark HRM</div>
{#                    <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot#}
{#                        password?</a></div>#}
                </div>

                <div style="padding-top:30px" class="panel-body">

                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                    <form class="login" method="POST" action="" >
                      {% csrf_token %}
                      {% bootstrap_form form %}

                      <button class="btn btn-success" type="submit">{% trans "Login" %}</button>
                    </form>

                </div>
            </div>
        </div>
    </div>






{% endblock %}

human_resource/accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}Log Out{% endblock %}

{% block content %}
<div class="col-sm-4 col-sm-offset-4" >
<h1>Log Out</h1>

<p>Are you sure you want to sign out?</p>

<form method="post" action="{% url 'accounts:logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit" class="btn btn-primary">Log Out</button>
</form>
</div>

{% endblock %}

human_resource/accounts/templates/accounts/password_change.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>

    <form method="POST" action="{% url 'account_change_password' %}" class="password_change">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="action">{% trans "Change Password" %}</button>
    </form>
{% endblock %}

human_resource/accounts/templates/accounts/password_reset.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'account_reset_password' %}" class="password_reset">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Reset My Password' %}" />
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>
{% endblock %}

human_resource/accounts/templates/accounts/password_reset_done.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}
    <h1>{% trans "Password Reset" %}</h1>
    
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}
    
    <p>{% blocktrans %}We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>
{% endblock %}

human_resource/accounts/templates/accounts/password_reset_from_key.html
{% extends "account/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% if token_fail %}{% trans "Bad Token" %}{% else %}{% trans "Change Password" %}{% endif %}</h1>

    {% if token_fail %}
        {% url 'account_reset_password' as passwd_reset_url %}
        <p>{% blocktrans %}The password reset link was invalid, possibly because it has already been used.  Please request a <a href="{{ passwd_reset_url }}">new password reset</a>.{% endblocktrans %}</p>
    {% else %}
        {% if form %}
            <form method="POST" action="{{ action_url }}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" name="action" value="{% trans 'change password' %}"/>
            </form>
        {% else %}
            <p>{% trans 'Your password is now changed.' %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

human_resource/accounts/templates/accounts/password_reset_from_key_done.html
{% extends "account/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>
    <p>{% trans 'Your password is now changed.' %}</p>
{% endblock %}

human_resource/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}

{% block head_title %}Signup{% endblock %}

{% block content %}

<div class="col-sm-4 col-sm-offset-4" >
<h1>Sign Up Now</h1>

<p>Already have an account? Then please <a href="{% url 'accounts:login' %}">Login In</a>.</p>

<form class="signup" id="signup_form" method="post" action="{% url 'accounts:signup' %}">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button class="btn btn-primary" type="submit" >Sign Up </button>
</form>
</div>
{% endblock %}

human_resource/accounts/templates/accounts/signup_closed.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Up Closed" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Up Closed" %}</h1>

<p>{% trans "We are sorry, but the sign up is currently closed." %}</p>
{% endblock %}

human_resource/accounts/templates/accounts/verification_sent.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Verify Your E-mail Address" %}{% endblock %}

{% block content %}
    <h1>{% trans "Verify Your E-mail Address" %}</h1>

    <p>{% blocktrans %}We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>

{% endblock %}

human_resource/accounts/templates/accounts/verified_email_required.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Verify Your E-mail Address" %}{% endblock %}

{% block content %}
<h1>{% trans "Verify Your E-mail Address" %}</h1>

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This part of the site requires us to verify that
you are who you claim to be. For this purpose, we require that you
verify ownership of your e-mail address. {% endblocktrans %}</p>

<p>{% blocktrans %}We have sent an e-mail to you for
verification. Please click on the link inside this e-mail. Please
contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>

<p>{% blocktrans %}<strong>Note:</strong> you can still <a href="{{ email_url }}">change your e-mail address</a>.{% endblocktrans %}</p>


{% endblock %}