human_resource/accounts/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from accounts.views import LoginView, SignupView, LogoutView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^signup/$', SignupView.as_view(), name='signup'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),

]

urlpatterns += staticfiles_urlpatterns()

human_resource/administration/urls.py
# import user

from django.conf.urls import url
from . import views

urlpatterns = [
    # user roles urls

    url(r'^$', views.UserRoleListView.as_view(), name='user_role_landing'),
    url(r"create$", views.CreateUserRoleView.as_view(), name='create_user_role'),

    #employee urls
    url(r'^$', views.EmployeeListView.as_view(), name='employee_landing'),
    url(r"create$", views.CreateEmployeeView.as_view(), name='create_employee'),

    # system users urls
    url(r'^$', views.UserListView.as_view(), name='user_landing'),
    url(r"create$", views.CreateUserView.as_view(), name='create_users'),

    # job titles urls
    url(r'^$', views.JobTitleListView.as_view(), name='job_title_landing'),
    url(r"create$", views.CreateUserView.as_view(), name='create_job_title'),

    # job category urls
    url(r'^$', views.JobCategoryListView.as_view(), name='job_category_landing'),
    url(r"create$", views.CreateJobCategoryView.as_view(), name='create_job_category'),

    # work shifts urls
    url(r'^$', views.WorkShiftListView.as_view(), name='work_shift_landing'),
    url(r"create$", views.CreateWorkShiftView.as_view(), name='create_work_shift'),

]

human_resource/human_resource/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from human_resource import views

urlpatterns = [
    url(r'^$', views.home, name='landing'),
    url(r'^admin_menu/', views.admin_menu, name='admin_menu'),

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^administration/', include('administration.urls', namespace='administration')),

]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

human_resource/templates/admin_menu.html
{% extends 'base.html' %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav">
                    <li class="dropdown accordion">
                        <a href="#" class="dropdown-toggle link" data-toggle="dropdown" role="button"
                           aria-haspopup="true"
                           aria-expanded="false">User Roles <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'administration:create_user_role' %}">Add User Roles</a></li>
                            <li><a href="{% url 'administration:user_role_landing' %}">User Roles</a></li>
                        </ul>
                    </li>
                    <li class="dropdown accordion">
                        <a href="#" class="dropdown-toggle link" data-toggle="dropdown" role="button"
                           aria-haspopup="true"
                           aria-expanded="false">Employees <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'administration:create_employee' %}">Add Employees</a></li>
                            <li><a href="{% url 'administration:employee_landing' %}">Available Employees </a></li>
                        </ul>
                    </li>
                    <li class="dropdown accordion">
                        <a href="#" class="dropdown-toggle link" data-toggle="dropdown" role="button"
                           aria-haspopup="true"
                           aria-expanded="false">Job Titles <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'administration:create_job_title' %}">Add Job Titles </a></li>
                            <li><a href="{% url 'administration:job_title_landing' %}">Job Titles </a></li>
                        </ul>
                    </li>
                    <li class="dropdown accordion">
                        <a href="#" class="dropdown-toggle link" data-toggle="dropdown" role="button"
                           aria-haspopup="true"
                           aria-expanded="false">Job Categories <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'administration:create_job_category' %}">Add Job Categories</a></li>
                            <li><a href="{% url 'administration:job_category_landing' %}">Job Categories</a></li>

                        </ul>
                    </li>
                    <li class="dropdown accordion">
                        <a href="#" class="dropdown-toggle link" data-toggle="dropdown" role="button"
                           aria-haspopup="true"
                           aria-expanded="false">Work Shifts <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'administration:create_work_shift' %}">Add Work Shifts</a></li>
                            <li><a href="{% url 'administration:work_shift_landing' %}">Available Work Shifts</a></li>

                        </ul>
                    </li>
                </ul>

            </div><!-- /.navbar-collapse -->

        </div><!-- /.container-fluid -->
    </nav>
    </body>
    </html>
{% endblock %}

human_resource/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HRM</title>

    {#            <link href="{% static 'css/main.css' %}" rel="stylesheet"/>#}
    {#    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>#}
    <link rel="stylesheet" href="{% static 'css/landing_page/landing.css' %}">
    <link rel="stylesheet" href="{% static 'css/landing_page/bootstrap.min.css' %}">
    <style type="text/css">
        .fa-search {
        }
    </style>

    {#        <link rel="stylesheet" href="{% static 'css/main.css' %}">#}
</head>
<body>


<!--Top Navbar-->

<div class="wrap">
    <img src="{% static 'img/SPARKFINAL.jpg' %}"/>
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <form class="navbar-form pull-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav pull-right"  style="padding-right: 5%">
                    <li class="dropdown accordion">
                        <a href="#" class="dropdown-toggle link" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Accounts <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Profile</a></li>
                            <li><a href="#">Logout</a></li>
                            <li><a href="#">Change Password</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
    </nav>
    <!--End of Top Navbar-->

    <!--SideMenu-->
    <nav id="side-menu" class="aside" role="navigation">
        <ul class="nav nav-list accordion">
            <li class="nav-header">
                <a class="link">Dashboard</a>
                <a href="{% url 'administration:user_landing' %}" class="link">PIM</a>
                <a class="link">Recruitment</a>
                <a class="link">Leave</a>
                <a class="link">PayRoll</a>
                <a class="link">Time</a>
                <a class="link">Performance</a>
                <a href="{% url 'admin_menu' %}" class="link">Admin</a>
            </li>
        </ul>
    </nav>
    <!--End of sideMenu-->

    <!--Body content-->
    <div class="content">
        <section class="content-inner">
            {% block content %}{% endblock %}

        </section>
    </div>
</div>
<footer class="navbar-fixed-bottom panel-footer">
    <div class="container">
        <p class="navbar-text pull-left">© 2017 - Spark HRM.
            <a href="http://moap.co.ug" target="_blank">MOAP UGANDA LIMITED</a>
        </p>

        <a class="navbar-text pull-right" href="http://moap.co.ug/support">Contact Us</a>
        <a class="navbar-text pull-right" href="#">Privacy & Terms</a>
    </div>
</footer>

</body>


<script src="{% static 'js/jquery-3.1.1.min.js' %}" type="text/javascript"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
<script>

</script>
</html>

human_resource/templates/landing.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{#{% block content %}#}
{#{% if request.user.is_authenticated %}#}


<style type="text/css">
    #search_block_top {
    }
</style>
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap.min.css' %}"/>
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>

</head>

<body>

<h1 align="center">Available Products</h1>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {#                <a class="navbar-brand" href="#">Brand</a>#}
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
    </div><!-- /.container-fluid -->
</nav>

</body>
{##}
{#{% else %}#}
{#    <a href="{% url 'accounts:login' %}">Login</a>#}
{#{% endif %}#}